// <auto-generated />
namespace DeviceBaseSystem.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DevceCompany_AddDesc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DevceCompany_AddDesc));
        
        string IMigrationMetadata.Id
        {
            get { return "201607062306583_DevceCompany_AddDesc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
